import type { NextPage } from 'next';

import Head from 'next/head';
import { Flex } from '@chakra-ui/react';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  console.info('user is logged in:', session);
  console.info('user is status is:', status);

  return (
    <Flex
      flex={1}
      backgroundColor="blue.600"
      marginX="auto"
      justifyContent="center"
      position="relative"
    >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        backgroundColor="blue.600"
        height="100%"
        width="100%"
        flex={1}
        maxWidth="2560px"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
        padding={2}
      ></Flex>
    </Flex>
  );
};

export default Home;
