import type { NextPage } from 'next';

import { Link, Text, Icon } from '@chakra-ui/react';
import Head from 'next/head';
import { AiFillGithub } from 'react-icons/ai';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Text color="purple.900" fontSize={32}>
          Welcome to{' '}
          <Link color="pink" href="https://nextjs.org">
            Next.js!
          </Link>
        </Text>

        <Icon as={AiFillGithub} width={60} height={60} fill="pink" />
      </main>
    </div>
  );
};

export default Home;
